spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-xv6hd61k.us.auth0.com/}

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.github.smsilva.wasp.demo.springsecuritydemo: ${APP_LOGGING_LEVEL:TRACE}
